name: Build wheels

on:
  workflow_call:

env:
  UV_VERSION: 0.8.3
  PYTHON_VERSION: 3.12

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Install uv
        uses: astral-sh/setup-uv@bd01e18f51369d5a26f1651c3cb451d3417e3bba  # v6.3.1
        with:
          version: "${{ env.UV_VERSION }}"
          python-version: "${{ env.PYTHON_VERSION }}"
          enable-cache: 'true'
          cache-suffix: "${{ env.PYTHON_VERSION }}"

      - name: Build wheel and source distribution
        run: |
          uv build

      - name: Publish
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc  # v1.12.4
        with:
          packages-dir: dist
          skip-existing: true
          verbose: true

